### ISSUE TITLE
Validation Error in RTBHouse Python SDK: impsCount Should Be Integer

### ISSUE THREAD

**Issue by hemansah** [rtbhouse-apps/rtbhouse-python-sdk#134]
We encountered a validation error when using the RTBHouse Python SDK to fetch RTB stats. 
The error log indicates that the **impsCount** field received a float value instead of an integer, causing a validation failure in the Pydantic model.

```
api = Client(auth=BasicAuth(username, password))
stats = api.get_rtb_stats(advertiser.hash, start_date_, end_date_, group_by, metrics, count_convention=CountConvention.ATTRIBUTED_POST_CLICK)
```

**requirements.txt**
rtbhouse-sdk==11.1.0
pydantic==2.5.2
pydantic_core==2.14.5

Possible [source](https://github.com/rtbhouse-apps/rtbhouse-python-sdk/blob/37ad31a47aef6d016df1f382aee29001690dc212/rtbhouse_sdk/schema.py#L243C5-L243C37) of error:
`imps_count: Optional[int] = None`

**Comment by peku33** [comment]
@hemansah, thank your for reporting, I can confirm this issue. We should get back to you with update soon.
