### ISSUE TITLE
pydantic.error_wrappers.ValidationError: 1 validation error for Conversion

### ISSUE THREAD

**Issue by adamjuraczarnecki** [rtbhouse-apps/rtbhouse-python-sdk#145]
pydantic.error_wrappers.ValidationError: 1 validation error for Conversion
lastImpressionTime
  none is not an allowed value (type=type_error.none.not_allowed)
  
  
  a taką daną dostaję z api. Więc jakby libka nie obsługuje tego co może zrobić serwer

**Comment by peku33** [comment]
@adamjuraczarnecki, z której wersji korzystasz? Od wersji `11.0.0` to pole jest nullowalne.
