### ISSUE TITLE
group by lacks userSegments

### ISSUE THREAD

**Issue by cibureau** [rtbhouse-apps/rtbhouse-python-sdk#15]
Hi,
we are running into an error when using the new API version
 
api.get_rtb_stats(advertisers[0]['hash'], day_from, day_to, ['day','subcampaign','userSegments'], include_dpa=True)

We can use the filter "user_segments=",
but we cannot retrieve userSegments as a column in the answerset (as we did before).

In your documentation we have seen that you changed campaign to subcampaign.
Did you rename here, too?

regards,
Lars

**Comment by kamilglod** [comment]
@cibureau sorry for a long time without reply. 
If you examine an error that is thrown by this method you will see that under the `errors` attribute there is an explanation: `{'groupBy': 'Invalid values: userSegments. Allowed values: userSegment, subcampaign, category, creative, country, day, deviceType, year, month'}`

So you need to change `userSegments` to `userSegment` in group by list. But additionally you cannot group by user segment and include dpa stats in the same call (this is limitation of our API). So the finally call may look like this:
```python
data = api.get_rtb_stats(advertiser_hash, day_from, day_to, ['day','subcampaign'], include_dpa=True)
data2 = api.get_rtb_stats(advertiser_hash, day_from, day_to, ['day','subcampaign','userSegment'])
```
