### ISSUE TITLE
campaignCost not matching in get_rtb_device_stats method

### ISSUE THREAD

**Issue by felipemiquelim** [rtbhouse-apps/rtbhouse-python-sdk#9]
When breaking by device via `get_rtb_device_stats`, the sum of `campaignCost` column is not the same as the total provided by RTBPanel and other methods in API, such as `get_campaign_stats_total`

**Comment by kamilglod** [comment]
Please report only issues connected with SDK code, in case of problems with API please contact support@rtbhouse.com.
